twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - bootstrap_4_layout.html.twig 
    globals:
        # permet de difinir des variables globales pour tous les template twig
        #Il est préférable de créer une classe nous même, étendue depuis CategoryRepository que nous integrerons ici
        # mais cela marche avec CategoryRepository egalement
        categoryRepository: "@App\\Repository\\CategoryRepository" 
        cartService: "@App\\Cart\\CartService"

when@test:
    twig:
        strict_variables: true
