# App\Entity\Product:
#   properties:
#     name: 
#       - NotBlank: {message: "Le nom du produit est obligatoire"}
#       - Length: 
#           {
#             min: 3,
#             max: 255,
#             minMessage: "Le nom du produit doit comporter au moins 3 caractères",
#             maxMessage: "Le nom du produit ne doit pas dépasser 255 caractères"
#           }
#     price:
#       - NotBlank: {message: "Le prix du produit doit être renseigné"}